# Generated by Django 2.2.10 on 2020-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200712_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_tag',
            name='main_tag_for_article',
            field=models.BooleanField(default=False),
        ),
    ]
