# Generated by Django 2.2.10 on 2020-07-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200716_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_tag',
            old_name='main_tag_for_article',
            new_name='is_main',
        ),
    ]
